export const IS_TEST = process.env.NODE_ENV === 'test'
export const APP_VER = process.env.REACT_APP_NADYA_VER || 'dev'
export const USER_ID_FROM_LS = '@nadya:userId'
export const SUBSCRIPTIONS = 'subscriptions'
export const USER = 'user'
